name: Run Dagster Assets

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on PRs to the main branch
  workflow_dispatch: # Allows manual trigger

# The jobs that will run as part of this workflow
jobs:
  run-dagster-assets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Run Dagster Assets
      run: make run_dagster_assets  # Run the make target